<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray($colonne, $ordre, $keyword=null) {
        $qb = $this->createQueryBuilder('p');
        if (!empty($keyword)) {
            $qb->where('p.title LIKE :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        $query = $qb
            ->orderBy('p.'.$colonne, $ordre)
            ->getQuery();
        return $query->getArrayResult();
    }

    public function search($keyword)
    {
        $query = $this->createQueryBuilder('p')->
            where('p.title LIKE \'%' . $keyword . '%\'')
            ->getQuery();
        return $query->getArrayResult();
    }
}
